services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
      - ./config:/root/.minio

  mc:
    image: bitnami/minio-client:latest
    container_name: minio-client
    depends_on:
      - minio
    environment:
      MINIO_SERVER: http://minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: |
      /bin/sh -c "
      sleep 15 &&
      mc alias set minio1 http://minio:9000 minioadmin minioadmin &&
      mc alias list &&
      mc admin info minio1 &&
      mc mb minio1/bucket1 &&
      mc mb minio1/bucket2 &&
      mc policy set public minio1/bucket1 &&
      mc policy set private minio1/bucket2 &&
      mc ls minio1 &&
      echo 'Buckets created!'
      "
